### PR TITLE
Remove debug configuration files from the three applications

### PR DESCRIPTION
**Pull request by cooperaj**
(public, caseworker, api)

## Purpose
For some reason the development files had been commited, they also had some extra stuff added despite instructions to not edit the files and enable/disable them for local dev only using a set of composer commands.

Fixes LPA-3565

## Approach

Remove some files.

## Learning

Always read the instructions

## Checklist

* [x] I have performed a self-review of my own code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] The product team have tested these changes

### CODE REVIEW

**Comment by andrewpearce-digital** [comment]
Would it help to update the .gitignore too, to make sure they don't get added again? 
Will probably need to do a `git rm --cached <file>` as the files were previously tracked.

**Comment by cooperaj** [comment]
> We should update the .gitignore too, to make sure they don't get added again?
> Will probably need to do a `git rm --cached <file>` as the files were previously tracked.

The file should not be added again as it was created manually. The process to enable development mode actually makes a differently named file which is already ignored by the .gitignore in the folder adjacent.

**Comment by williamfalconeruk** [comment]
> will approve - but what file locally do we need, and will we need to .gitignore that file? i'm thinking this will definitely be needed on local debug somewhere

above comment superseded.

**Comment by cooperaj** [comment]
> will approve - but what file locally do we need, and will we need to .gitignore that file? i'm thinking this will definitely be needed on local debug somewhere

Standard debug enable instructions for Zend Expressive. Listed in the `development.config.php.dist` file. I think it's something like `composer development-enable`

**Comment by williamfalconeruk** [comment]
> > will approve - but what file locally do we need, and will we need to .gitignore that file? i'm thinking this will definitely be needed on local debug somewhere
> 
> Standard debug enable instructions for Zend Expressive. Listed in the `development.config.php.dist` file. I think it's something like `composer development-enable`

thanks, useful info.

**Pull request merged**
